name: Debate Dataset Training Pipeline

# Trigger the workflow on push to main branch and pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  download-and-train:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydantic pyyaml typing-extensions
        pip install kaggle pandas numpy scikit-learn
        pip install -e .
        
    - name: Setup Kaggle credentials
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        mkdir -p ~/.kaggle
        echo '{"username":"'$KAGGLE_USERNAME'","key":"'$KAGGLE_KEY'"}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        
    - name: Download datasets
      run: |
        # Create datasets directory
        mkdir -p datasets
        
        # Download UN General Debates dataset
        echo "Downloading UN General Debates dataset..."
        kaggle datasets download -d unitednations/un-general-debates -p datasets/ --unzip
        
        # Download SOHO Forum Debate Results dataset  
        echo "Downloading SOHO Forum Debate Results dataset..."
        kaggle datasets download -d martj42/the-soho-forum-debate-results -p datasets/ --unzip
        
        # Download UN General Debate Corpus 1946-2023 dataset
        echo "Downloading UN General Debate Corpus dataset..."
        kaggle datasets download -d namigabbasov/united-nations-general-debate-corpus-1946-2023 -p datasets/ --unzip
        
        # List downloaded files for verification
        echo "Downloaded files:"
        find datasets/ -type f -name "*.csv" -o -name "*.json" -o -name "*.txt" | head -20
        
    - name: Run debate model training
      run: |
        echo "Starting debate model training..."
        python scripts/train_debate_model.py
        
    - name: Upload training artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: training-artifacts
        path: |
          training_output/
          *.log
        retention-days: 30
        
    - name: Run basic tests
      run: |
        # Run existing tests to ensure nothing is broken
        python -m pytest tests/test_p0_implementation.py -v